#pragma once

#include <gl/glew.h>

enum class GLType {
    BYTE = GL_BYTE,
    UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
    SHORT = GL_SHORT,
    UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
    INTEGER = GL_INT,
    UNSIGNED_INT = GL_UNSIGNED_INT,
    FLOAT = GL_FLOAT,
    DOUBLE = GL_DOUBLE,
    HALF_FLOAT = GL_HALF_FLOAT,
    UNSIGNED_332 = GL_UNSIGNED_BYTE_3_3_2,
    UNSIGNED_233R = GL_UNSIGNED_BYTE_2_3_3_REV
};